config/routes.rb
Rails.application.routes.draw do

  root 'surveys#index'
  resources 'surveys'
  resources 'attempts'
  resources 'users', only: [:create]

  delete 'attempts/:survey_id/:user_id' => 'attempts#delete_user_attempts', as: :delete_user_attempts
  post 'user/:id/change_name' => 'users#change_name', as: :change_user_name

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, length: { maximum: 30 }, presence: true
  has_surveys
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController

  helper 'surveys'

  before_filter :load_survey, only: [:new, :create]

  def index
    @surveys = Survey::Survey.active
  end

  def show
    @attempt = Survey::Attempt.find_by(id: params[:id])
    render :access_error if current_user.id != @attempt.participant_id
  end

  def new
    @participant = current_user

    unless @survey.nil?
      @attempt = @survey.attempts.new
      @attempt.answers.build
    end
  end

  def create
    @attempt = @survey.attempts.new(params_whitelist)
    @attempt.participant = current_user
    if @attempt.valid? && @attempt.save
      correct_options_text = @survey.correct_options.present? ? 'Bellow are the correct answers marked in green' : ''
      redirect_to attempt_path(@attempt.id), notice: "Thank you for answering #{@survey.name}! #{correct_options_text}"
    else
      build_flash(@attempt)   
      @participant = current_user
      render :new
    end
  end

  def delete_user_attempts
    Survey::Attempt.where(participant_id: params[:user_id], survey_id: params[:survey_id]).destroy_all
    redirect_to new_attempt_path(survey_id: params[:survey_id])
  end

  private

  def load_survey
    @survey = Survey::Survey.find_by(id: params[:survey_id])
  end

  def params_whitelist
    if params[:survey_attempt]
      params[:survey_attempt][:answers_attributes] = params[:survey_attempt][:answers_attributes].map { |attrs| { question_id: attrs.first, option_id: attrs.last } }
      params.require(:survey_attempt).permit(Survey::Attempt::AccessibleAttributes)
    end
  end

  def current_user
    view_context.current_user
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  before_filter :load_survey, only: [:show, :edit, :update, :destroy]

  def index
    type = view_context.get_survey_type(params[:type])
    query = if type then Survey::Survey.where(survey_type: type) else Survey::Survey end
    @surveys = query.order(created_at: :desc).page(params[:page]).per(15)
  end

  def new
    @survey = Survey::Survey.new(survey_type: view_context.get_survey_type(params[:type]))
  end

  def create
    @survey = Survey::Survey.new(params_whitelist)
    if @survey.valid? && @survey.save
      default_redirect
    else
      build_flash(@survey)
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @survey.update_attributes(params_whitelist)
      default_redirect
    else
      build_flash(@survey)
      render :edit
    end
  end

  def destroy
    @survey.destroy
    default_redirect
  end

  private

  def default_redirect
    redirect_to surveys_path, notice: I18n.t("surveys_controller.#{action_name}")
  end

  def load_survey
    @survey = Survey::Survey.find(params[:id])
  end

  def params_whitelist
    params.require(:survey_survey).permit(Survey::Survey::AccessibleAttributes << :survey_type)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    session[:user_id] = User.create(user_params).id
    redirect_to :back
  end

  def change_name
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to :back
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def build_flash model
    if model.errors.count > 0
      flash.now[:alert] = model.errors.full_messages.join('<br/>').html_safe
    end
  end

  def correct_flash_name name
    case name
    when 'alert'
      'danger'
    when 'notice'
      'success'
    else
      name
    end
  end

  def is_active?(link_path)
    current_page?(link_path) ? 'active' : nil
  end

  def current_user
    @user ||= User.find_by(id: session[:user_id])
  end

  def user_form
    common_options = { validate: true, html: { class: 'user-form' } }
    form_options = current_user ? [ current_user, { url: change_user_name_path(current_user.id), method: :post, validate: true }.merge(common_options) ] : [ User.new, { validate: true }.merge(common_options) ]
    form_for *form_options do |f|
      yield f
    end
  end

  private
  
  def number_of_people_who_also_answered_count option_id
    Survey::Answer.where(option_id: option_id).count
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
  def link_to_remove_field(name, f)
    f.hidden_field(:_destroy) +
    __link_to_function(raw(name), "removeField(this)", :id =>"remove-attach", class: 'btn btn-default')
  end

  def new_survey
    new_survey_path
  end

  def edit_survey(resource)
    edit_survey_path(resource)
  end

  def survey_scope(resource)
    if action_name =~ /new|create/
      surveys_path(resource)
    elsif action_name =~ /edit|update/
      survey_path(resource)
    end
  end

  def attempt_scope(resource)
    if action_name =~ /new|create/
     attempts_path(resource)
    elsif action_name =~ /edit|update/
      attempt_path(resource)
    end
  end

  def link_to_add_field(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object,:child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    __link_to_function(name, "addField(this, \"#{association}\", \"#{escape_javascript(fields)}\")",
    :id=>"add-attach",
    :class=>"btn btn-default")
  end

  def get_answer_fields attempt
    attempt.survey.questions.map { |q| Survey::Answer.new(question_id: q.id) }
  end

  def the_chosen_one? answer, option
    if answer.option_id == option.id then 'chosen' else nil end
  end

  def number_of_people_who_also_answered option_id
    count = number_of_people_who_also_answered_count(option_id)
    "<span class='number'> #{count} </span> #{'answer'.pluralize}".html_safe
  end

  def get_color_of_option answer, option
    if is_quiz?(answer.question.survey.survey_type)
      if option.correct
        'bg-success'
      elsif the_chosen_one?(answer, option)
        'bg-danger'
      end
    elsif is_score?(answer.question.survey.survey_type)
      get_weight_html_class option
    end
  end

  def get_survey_type survey_type
    get_survey_types[survey_type] || get_survey_types.invert[survey_type]
  end

  def get_survey_types
    { 0 => 'quiz',
      1 => 'score',
      2 => 'poll' }
  end

  def is_quiz? something
    something == 0 || something == 'quiz'
  end

  def is_score? something
    something == 1 || something == 'score'
  end

  def is_poll? something
    something == 2 || something == 'poll'
  end

  def get_weight option
    return unless is_score?(option.question.survey.survey_type)
    option.weight > 0 ? "(+#{option.weight})" : "(#{option.weight})"
  end

  def get_weight_html_class option
    return 'bg-warning' if option.weight == 0
    option.weight > 0 ? 'bg-success' : 'bg-danger'
  end

  def surveys_count type = get_survey_types.keys
    Survey::Survey.where(survey_type: type).count
  end

  def number_of_questions survey
    survey.questions.count
  end

  def number_of_attempts survey
    survey.attempts.count
  end

  private

  def __link_to_function(name, on_click_event, opts={})
    link_to(name, 'javascript:;', opts.merge(onclick: on_click_event))
  end

  def has_weights? survey
    survey.questions.map(&:options).flatten.any? { |o| o.weight != 0 }
  end
end

app/views/attempts/_form.html.erb
<div class="panel panel-info" style="margin-top: 2%;"> 
  <div class="panel-heading"><%= @survey.name %></div> 
    <div class="panel-body"> 
      <i><%= @attempt.survey.description %></i> 
    </div>
</div>
<ul class="list-group">
 <%= form_for(@attempt, url: attempt_scope(@attempt)) do |f| %>
  <%= hidden_field_tag :survey_id, @survey.id %>
    <%= f.fields_for :answers, get_answer_fields(@attempt) do |answer_fields| %>
    <% question = answer_fields.object.question %>
    <div class="panel panel-default"> 
      <div class="panel-heading"><%= question.text %></div> 
        <div class="panel-body"> 
          <%= collection_radio_buttons('survey_attempt[answers_attributes]', question.id, question.options, :id, :text) do |b| %>
            <li class="list-group-item">
              <%= b.label { b.radio_button + b.text } %>
            </li>
          <% end %>
        </div>
    </div>
    <% end -%>
  <%= f.submit "SUBMIT", class: 'btn btn-info' %>
  <% end -%>
</ul>

app/views/attempts/access_error.html.erb
<div class="container">
  <p> You do not have access to this page </p>
</div>

app/views/attempts/new.html.erb
<div class="container">
  <% if @survey.nil? %>
    <p>
      This survey is no longer available
    </p>
  <% elsif @survey.avaliable_for_participant?(@participant) %>
    <%= render 'form' %>
  <% else %>
    <p>
      You have spent all the possible attempts to answer this Survey
    </p>
    <p>
      <%= link_to delete_user_attempts_path(@survey.id, session[:user_id]), method: :delete do %>
        Click here to reset the attempts
      <% end %>
    </p>
  <% end -%>
</div>

app/views/attempts/show.html.erb
<div class="container">
  <h2 class="survey-title">
    <%= @attempt.survey.name %>
    <p><small><%= @attempt.survey.description %></small></p>
  </h2>
  <ol class="questions">
    <% @attempt.answers.each do |answer| %>
      <li>
        <p class="question"> <%= answer.question.text %> </p>
        <ul class="options">
          <% answer.question.options.each do |option| %>
            <li class="radio">
              <label>
                <%= radio_button_tag '', '', the_chosen_one?(answer, option), disabled: true %>
                <% color = get_color_of_option(answer, option) %>
                <span class="<%= color %> <%= the_chosen_one?(answer, option) %>"> <%= option.text %> <%= get_weight(option) %> </span>
              </label>
              <!-- <p class="answers-number"> <%= number_of_people_who_also_answered(option.id) %> </p> -->
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  <ol>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Progressive Techies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/submit_name_modal' %>
<%= render 'shared/navbar' %>
<%= render 'shared/flash' %>
<%= yield %>
<%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_flash.html.erb
<div class="container">
  <div class="flash">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= correct_flash_name(name) %>" role="alert">
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Copyright © <%= Time.now.year %>  <%= link_to 'Progressive Techies', 'http://www.facebook.com/progtechies', target: '_blank' %></p>
  </div>
</footer>

app/views/shared/_gem_header_info.html.erb
<div class="gem-info">
  <div class="container">
    <div class="text text-muted">
      This is a demo app for the <%= link_to 'Survey', 'https://github.com/runtimerevolution/survey', target: '_blank' %> gem
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header>
  <div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to surveys_path, class: 'navbar-brand' do %>
          <%= render 'shared/rr_logo' %>
        <% end -%>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="<%= is_active?(surveys_path) %>">
            <%= link_to surveys_path do %>
              All surveys
              <span class='badge'> <%= surveys_count %> </span>
            <% end -%>
          </li>
          <li class="dropdown <%= is_active?(new_survey_path) %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">New survey <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li> <%= link_to 'Opinion Poll', new_survey_path(type: 'poll') %> </li>
              <li> <%= link_to 'Quiz', new_survey_path(type: 'quiz') %> </li>
              <li> <%= link_to 'Score Survey', new_survey_path(type: 'score') %> </li>
            </ul>
          </li>
        </ul>
        <% if current_user %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <p class="navbar-text">
                Logged in as:
                <b> <%= current_user.name %> </b>
                <%= link_to '(change name)', '#', 'data-toggle': 'modal', 'data-target': '#submit-name-modal' %>
              </p>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_submit_name_modal.html.erb
<div id="submit-name-modal" class="modal fade" data-new-user="<%= !current_user %>">
  <%= user_form do |f| %>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <h4> <%= f.label :name, 'What\'s your name?' %> </h4>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon">
                <i class="fa fa-user"></i>
              </span>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <span class="help-block">This is your username. It will be associated with each survey participation you make</span>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/surveys/_form.html.erb
<%= form_for(@survey, url: survey_scope(@survey), html: { class: 'survey-form clearfix' }, validate: true) do |f| %>
  <%= f.hidden_field :survey_type, value: @survey.survey_type %>
  <div class='field'>
    <div class='row'>
      <div class='form-group col-sm-4'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class='form-group col-sm-4'>
        <%= f.label :attempts_number, 'Maximum number of attempts (0 is infinite)' %>
        <%= f.number_field :attempts_number, min: 0, class: 'form-control' %>
      </div>
      <div class='form-group col-sm-4'>
        <%= f.label :active %>
        <%= f.select :active, ['true', 'false'], {}, class: 'form-control' %>
      </div>
    </div>
    <div class='row'>
      <div class='form-group col-sm-12'>
        <%= f.label :description %>
        <%= f.text_area :description, size: '100x5', class: 'form-control', style: 'max-width: 100%;' %>
      </div>
    </div>
    
    <div class='appendable'>
      <% if is_score?(@survey.survey_type) %>
        <br/>
        <div> In this type of survey, you have to enter a score for each question option (negative values are allowed) </div>
      <% end -%>
      <%= f.fields_for :questions do |builder| %>
        <%= render 'question_fields', f: builder %>
      <% end %>
    </div>
    <br/>
    <%= link_to_add_field 'Add a new Question', f, :questions %>
  </div>
  <%= f.submit 'Submit', class: 'pull-right btn btn-primary' %>
  <% end -%>
</div>

<script type='text/javascript'>
  // remove attachment field
  function removeField(link) {
    $(link).prev("input[type=hidden]").val("true");
    tag = $(link).closest(".field")
    tag.hide('slow');
  }

  // add attachment field
  function addField(link, association, content) {
    var new_id = new Date().getTime();
    var regexp = new RegExp("new_" + association, "g");
    var html = $(content.replace(regexp, new_id)).hide();
    var target = $(link).closest("div.field").find(".appendable").first();

    var last_height = 0
    html.appendTo(target).slideDown({
      duration: 'slow',
      progress: function () {
        delta = $(this).outerHeight(true) - last_height
        $(window).scrollTop( $(window).scrollTop() + delta );
        last_height = $(this).outerHeight(true);
      },
      complete: function () {
        $(this).find('input[type=text]').focus();
      }});
    }
</script>

app/views/surveys/_input_quiz.html.erb
<div class="checkbox col-xs-3 col-sm-2">
  <%= f.label :correct do %>
    <%= f.check_box :correct %>
    Correct answer
  <% end %>
</div>

app/views/surveys/_input_score.html.erb
<div class='form-group col-xs-3 col-sm-2'>
  <%= f.label :weight, class: 'sr-only' %>
  <%= f.number_field :weight, placeholder: 'weight', class: 'form-control' %>
</div>

app/views/surveys/_option_fields.html.erb
<div class="field">
  <div class="row">
    <div class="form-group col-xs-4">
      <%= f.label :text, class: 'sr-only' %>
      <%= f.text_field :text, placeholder: 'answer', class: 'form-control' %>
    </div>
    <%= render "input_#{get_survey_type(@survey.survey_type)}", f: f %>
    <div class="col-xs-4">
      <%= link_to_remove_field "Remove", f %>
    </div>
  </div>
</div>

app/views/surveys/_question_fields.html.erb
<div class='field clearfix'>
  <hr/>
  <h4>Question</h4>
  <div class='row'>
    <div class='form-group col-sm-4'>
      <%= f.label :text, class: 'sr-only' %>
      <%= f.text_field :text, placeholder: 'question', class: 'form-control' %>
    </div>
  </div>
  <ol class='appendable'>
    <%= f.fields_for :options do |builder| %>
      <%= render 'option_fields', :f => builder %>
    <% end -%>
  </ol>
  <%= link_to_add_field 'Add option', f, :options %>
  <%= link_to_remove_field 'Remove question', f %>
</div>

app/views/surveys/_survey.html.erb
<tr class="survey">
  <td class="table-center"> <%= render 'survey_label', survey_type: survey.survey_type %> </td>
  <td> <%= link_to survey.name, new_attempt_path(survey_id: survey.id), class: 'survey-name' %> </td>
  <td> <span class="survey-description"> <%= "#{survey.description}" %> </span> </td>
  <td class="table-center"> <%= number_of_questions(survey) %> </td>
  <td class="table-center"> <%= number_of_attempts(survey) %> </td>
  
  <td class="table-center survey-buttons">
    <div class="btn-group" role="group">
      <%= link_to edit_survey_path(survey.id), class: 'btn btn-default btn-sm' do %>
        <i class="fa fa-pencil-square-o"> Edit</i>
      <% end %>

      <%= link_to survey_path(survey.id), class: 'btn btn-default btn-sm', method: :delete, data: {confirm: "Are you sure you want to delete this survey?"} do %>
        <i class="fa fa-trash-o"> Delete</i>
      <% end %>
    </div>
  </td>
</tr>

app/views/surveys/_survey_label.html.erb
<% string_type ||= get_survey_type(survey_type) %>
<% with_badges ||= nil %>
<% if !with_badges || (with_badges && surveys_count(survey_type) > 0) %>
  <%= link_to surveys_path(type: string_type), class: "label label-survey label-survey-#{string_type} #{'label-with-badges' if with_badges}" do %>
    <span><%= string_type.capitalize %></span>
    <% if with_badges %>
      <span class='badge label-badge label-badge-<%= string_type %>'><%= surveys_count(survey_type) %></span>
    <% end %>
  <% end %>
<% end %>

app/views/surveys/_survey_label_all.html.erb
<%= link_to surveys_path, class: "label label-survey label-survey-all label-with-badges" do %>
  <span> All </span>
  <span class='badge label-badge label-badge-all'> <%= surveys_count %> </span>
<% end %>

app/views/surveys/edit.html.erb
<div class="container">
  <h2>
    Edit Survey
    <small> <%= render 'survey_label', survey_type: @survey.survey_type %> </small>
  </h2>
  <%= render 'form' %>
</div>

app/views/surveys/index.html.erb
<div class="container">
  <div class="questionnaires_<%= action_name %>">
    <h1>
      Surveys
    </h1>
    <hr>
    <% if @surveys.empty? %>
      <p> There are no surveys </p>
    <% else %>
      <p>
        Filter by type:
        <%= render 'survey_label_all' %>
        <%= render partial: 'survey_label', collection: get_survey_types.keys, as: :survey_type, locals: { with_badges: true } %>
      </p>
      <table class='table table-nonfluid survey-table'>
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Description</th>
            <th>Questions</th>
            <th>Participants</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: 'survey', collection: @surveys %>
        </tbody>
      </table>
      <%= paginate @surveys %>
    <% end %>
  </div>
</div>

app/views/surveys/new.html.erb
<div class="container">
  <h2>
    New Survey
    <small> <%= render 'survey_label', survey_type: @survey.survey_type %> </small>
  </h2>
  <hr/>
  <%= render 'form' %>
</div>